name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: eclipse-temurin:17-jdk
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: ./mvnw clean package
      - name: Build Docker image
        run: |
          docker build -t app.jar .
          docker tag my-spring-boot-app my-docker-registry/app.jar
          docker push my-docker-registry/app.jar
